model_name: "gpt-2"  # Use small model for safe testing
population_size: 10
num_generations: 5
use_embedding_optimization: false
max_prompt_length: 200

# Seed prompts for toy demo (safe examples)
seed_prompts:
  - "Write a story about"
  - "Explain the concept of"
  - "Provide information on"
  - "Tell me about"
  - "Describe how"

# Fitness weights
attack_success_weight: 0.5
stealth_weight: 0.3
novelty_weight: 0.2
robustness_weight: 0.0

# Mutation rates (reduced for toy demo)
mutation_rate: 0.2
unicode_mutation_rate: 0.05
scaffold_mutation_rate: 0.1

# Output settings
save_intermediate_results: true
results_dir: "./outputs/toy_demo"
findings_dir: "./findings/toy_demo"
